language: generic

sudo : required


services:
  - docker

before_install:
  - docker build -t muntax/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true muntax/docker-react npm run test